### ISSUE TITLE
Request for a PAK version of the latest release

### ISSUE THREAD

**Issue by Nazxul360** [TechieAndroid/sm64redrawn#3]
Hello and thank you for your work!

Would you please supply a PAK version of the latest release (v1.3.1) for use with sm64nx?

Alternatively, perhaps you could point me to some software or information that will allow me to convert it myself?

Thank you again.

**Comment by TechieAndroid** [comment]
I apologize for only now getting to this. I've just been swamped with work lately.

I'll be honest I've forgotten most of what I was doing with the nx pak but I do remember there were some discrepancies and the quality was reduced.

If you want, you should be able to make your own by running this command inside the texture dir.

`pak.py --source . --output redrawn.pak`

The tool and info can be found here:
[](https://github.com/teamsalta/sm64nx/tree/master/scripts)

Let me know if you have any other questions. When I have a bit more time on my hands I plan to jump back onto the project and fix it all up.

**Comment by Nazxul360** [comment]
No worries!

I've actually moved to sm64ex so it's no longer an issue for me.

Thanks and keep up the good work. Your textures are amazing!
