### ISSUE TITLE
Incomplete

### ISSUE THREAD

**Issue by Thirteen1355** [TechieAndroid/sm64redrawn#5]
Some textures, like almost all of them in Jolly Roger Bay, aren't redone at all. This thing seems incomplete, which is fine in and of itself, except the showcase video shows the ending of the game fully 'redrawn,' indicating the project is finished from start to end.

**Comment by TechieAndroid** [comment]
Hi Thirteen1355

This pack isn't complete. The readme mentions contributing. You're more than welcome to contribute to the pack on Discord with the rest of us if you want, we'd be glad to have another contributor.

The discord channel will also have information on updates.
